--
CREATE DATABASE ProjetoPatrimonios
GO 
USE ProjetoPatrimonios
GO

CREATE TABLE Cargo
(
CargoId					UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nome					VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TipoUsuario
(
TipoUsuarioId			UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nome					VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Cidade
(
CidadeId				UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeCidade				VARCHAR(50)
)
GO

CREATE TABLE Bairro
(
BairroId				UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeBairro				VARCHAR(30),
CidadeId				UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT BairroCidade_ID_FK FOREIGN KEY (CidadeId) REFERENCES Cidade(CidadeId) ON DELETE CASCADE
)

GO

CREATE TABLE Endereco
(
EnderecoId				UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Logradoura				VARCHAR(100) NOT NULL,
Numero					INT NOT NULL,
Complemento				VARCHAR(50),
CEP						VARCHAR(12) NOT NULL,
CidadeId				UNIQUEIDENTIFIER NOT NULL,
BairroId				UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT EnderecoBairro_ID_FK FOREIGN KEY (BairroId) REFERENCES Bairro(BairroId) ON DELETE CASCADE,
CONSTRAINT EnderecoCidade_ID_FK FOREIGN KEY (CidadeId) REFERENCES Cidade(CidadeId) ON DELETE CASCADE
)

GO

CREATE TABLE Usuario
(
UsuarioId				UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nome					NVARCHAR(100) NOT NULL,
Email					VARCHAR(150) NOT NULL,
RG						VARCHAR(15) NOT NULL,
CPF						NVARCHAR(12) NOT NULL,
CarteiraTrabalho		VARCHAR(14),

EnderecoId				UNIQUEIDENTIFIER NOT NULL,
CargoId					UNIQUEIDENTIFIER NOT NULL,
TipoUsuarioId			UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT UsuarioEndereco_ID_FK FOREIGN KEY (EnderecoId) REFERENCES Endereco(EnderecoId) ON DELETE CASCADE,
CONSTRAINT UsuarioCargo_ID_FK FOREIGN KEY (CargoId) REFERENCES Cargo(CargoId) ON DELETE CASCADE,
CONSTRAINT UsuarioTipoUsuario_ID_FK FOREIGN KEY (TipoUsuarioId) REFERENCES TipoUsuario(TipoUsuarioId) ON DELETE CASCADE
)
GO

CREATE TABLE StatusTransferencia
(
StatusTransferenciaId	UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
StatusTransferencia		VARCHAR(50) NOT NULL,
)
GO

CREATE TABLE StatusPatrimonio
(
StatusPatrimonioId	    UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
StatusPatrimonio		VARCHAR(50) NOT NULL,
)
GO

CREATE TABLE TipoPatrimonio
(
TipoPatrimonioId		UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeTipo                VARCHAR(50) NOT NULL
)

GO

CREATE TABLE Area
(
AreaId				    UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeArea                NVARCHAR(50) NOT NULL
)

GO

CREATE TABLE Local
(
LocalId					UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeLocal			    VARCHAR(50) NOT NULL,
LocalSAP			    INT NOT NULL,
DescricaoSAP		    VARCHAR(100) NOT NULL,
AreaId				    UNIQUEIDENTIFIER NOT NULL, 
CONSTRAINT LocalArea_ID_FK 
					FOREIGN KEY (AreaId) REFERENCES Area(AreaId) ON DELETE CASCADE
)

CREATE TABLE Patrimonio
(
PatrimonioId			UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Denominacao				VARCHAR(MAX) NOT NULL,
Valor					DECIMAL(10,2) NOT NULL,
NumeroSerie				VARCHAR(30) NOT NULL,
Imagem					VARCHAR(MAX) NULL,
LocalId					UNIQUEIDENTIFIER NOT NULL,
TipoPatrimonioId		UNIQUEIDENTIFIER NOT NULL,
StatusPatrimonioId		UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT PatrimonioLocal_ID_FK FOREIGN KEY(LocalId) REFERENCES Local(LocalId) ON DELETE CASCADE,
CONSTRAINT Patrimonio_TipoPatrimonio_ID_FK FOREIGN KEY(TipoPatrimonioId) REFERENCES TipoPatrimonio(TipoPatrimonioId) ON DELETE CASCADE,
CONSTRAINT Patrimonio_StatusPatrimonio_ID_FK FOREIGN KEY (StatusPatrimonioId) REFERENCES StatusPatrimonio(StatusPatrimonioId) ON DELETE CASCADE
)

GO

CREATE TABLE TipoAlteracao
(
TipoAlteracaoId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
NomeAlteracao NVARCHAR(50) NOT NULL,
)

CREATE TABLE LogPatrimonio
(
LogPatrimonioId		    UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
DataTransferencia		DATETIME2(0) NOT NULL,
Justificativa			VARCHAR(MAX) NOT NULL,
PatrimonioId			UNIQUEIDENTIFIER NOT NULL,
UsuarioId				UNIQUEIDENTIFIER NOT NULL,
LocalId					UNIQUEIDENTIFIER NOT NULL,
StatusPatrimonioId		UNIQUEIDENTIFIER NOT NULL,
TipoAlteracaoId			UNIQUEIDENTIFIER NOT NULL,


CONSTRAINT Log_Patrimonio_ID_FK FOREIGN KEY (PatrimonioId) REFERENCES Patrimonio(PatrimonioId) ON DELETE CASCADE,
CONSTRAINT Log_Usuario_ID_FK FOREIGN KEY (UsuarioId) REFERENCES Usuario(UsuarioId) ON DELETE CASCADE,
CONSTRAINT Log_Local_ID_FK FOREIGN KEY (LocalId) REFERENCES Local(LocalId) ON DELETE CASCADE,
CONSTRAINT Log_StatusPatrimonio_ID_FK FOREIGN KEY (StatusPatrimonioId) REFERENCES StatusPatrimonio(StatusPatrimonioId) ON DELETE CASCADE,
CONSTRAINT Log_TipoAlteracao_ID_FK FOREIGN KEY (TipoAlteracaoId) REFERENCES TipoAlteracao(TipoAlteracaoId) ON DELETE CASCADE
)

CREATE TABLE SolicitacaoTransferencia
(
SolicitacaoTransId		UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
DataSolicitacao			DATETIME2(0) NOT NULL,
DataResposta			DATETIME2(0) NOT NULL,
Justificativa			NVARCHAR(MAX) NOT NULL,
/*
TipoAlteracao 
*/

PatrimonioId			UNIQUEIDENTIFIER NOT NULL,
UsuarioSolicitandoId	UNIQUEIDENTIFIER NOT NULL,
UsuarioAprovacaoId		UNIQUEIDENTIFIER NOT NULL,
LocalId					UNIQUEIDENTIFIER NOT NULL,
StatusPatrimonioId		UNIQUEIDENTIFIER NOT NULL,

CONSTRAINT SolicitacaoTransferencia_Patrimonio_ID_FK FOREIGN KEY (PatrimonioId) REFERENCES Patrimonio(PatrimonioId) ON DELETE CASCADE,
CONSTRAINT SolicitacaoTransferencia_UsuarioSolicitacao_ID_FK FOREIGN KEY (UsuarioSolicitandoId) REFERENCES Usuario(UsuarioId) ON DELETE CASCADE,
CONSTRAINT SolicitacaoTransferencia_UsuarioAprovacao_ID_FK FOREIGN KEY (UsuarioAprovacaoId) REFERENCES Usuario(UsuarioId) ON DELETE CASCADE,
CONSTRAINT SolicitacaoTransferencia_Local_ID_FK FOREIGN KEY (LocalId) REFERENCES Local(LocalId) ON DELETE CASCADE,
CONSTRAINT SolicitacaoTransferencia_StatusPatrimonio_ID_FK FOREIGN KEY (StatusPatrimonioId) REFERENCES StatusPatrimonio(StatusPatrimonioId) ON DELETE CASCADE

)
